version: 2

linters:
  disable:
    - gci
    - wrapcheck
    - gomnd
    - scopelint
    - varnamelen
    - testpackage
    - tagliatelle
    - paralleltest
    - ireturn
    - goerr113
    - gochecknoglobals
    - exhaustivestruct
    - wsl
    - exhaustive
    - nosprintfhostport
    - nonamedreturns
    - interfacebloat
    - exhaustruct
    - lll
    - gosec
    - gomoddirectives
    - godox
    - gochecknoinits
    - funlen
    - dupl
    - cyclop
    # See https://github.com/golangci/golangci-lint/issues/3906
    - depguard
    # deprecated linters
    - deadcode
    - golint
    - interfacer
    - structcheck
    - varcheck
    - nosnakecase
    - ifshort
    - maligned
  enable-all: true
linters-settings:
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#dot-imports
      - name: dot-imports
        severity: warning
        disabled: true
