version: "2"

linters:
  default: all
  disable:
    - wrapcheck
    - gomnd
    - scopelint
    - varnamelen
    - testpackage
    - tagliatelle
    - paralleltest
    - ireturn
    - goerr113
    - gochecknoglobals
    - exhaustivestruct
    - wsl
    - exhaustive
    - nosprintfhostport
    - nonamedreturns
    - interfacebloat
    - exhaustruct
    - lll
    - gosec
    - gomoddirectives
    - godox
    - gochecknoinits
    - funlen
    - dupl
    - cyclop
    # See https://github.com/golangci/golangci-lint/issues/3906
    - depguard
    # deprecated linters (removed in v2)
    - deadcode
    - golint
    - interfacer
    - structcheck
    - varcheck
    - nosnakecase
    - ifshort
    - maligned
  settings:
    revive:
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#dot-imports
        - name: dot-imports
          severity: warning
          disabled: true

formatters:
  # Don't enable any formatters (gci would be enabled by default otherwise)
  enable: []
