version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # Essential for controllers - catches unchecked errors from client calls
    - errcheck
    # Standard Go vet checks
    - govet
    # Comprehensive static analysis
    - staticcheck
    # Security checks (overlaps with CodeQL but faster feedback)
    - gosec
    # Ineffectual assignments
    - ineffassign
    # Spelling mistakes in comments and strings
    - misspell
    # Opinionated linter with useful checks
    - gocritic
    # Detects naked returns in long functions
    - nakedret
    # Checks for unnecessary type conversions
    - unconvert
    # Reports unused code
    - unused
    # Checks for duplicate code
    - dupl
    # Checks error handling for common mistakes
    - errorlint
    # Catches common mistakes with nil errors
    - nilerr
    # Prevents loop variable capture issues
    - copyloopvar

  settings:
    errcheck:
      check-blank: true

    govet:
      enable-all: true
      disable:
        - fieldalignment

    staticcheck:
      checks:
        - all

    gosec:
      excludes:
        - G104  # Errors unhandled - covered by errcheck
        - G304  # File path provided as taint input
        - G402  # TLS InsecureSkipVerify - ok in tests

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - commentedOutCode

    nakedret:
      max-func-lines: 30

    dupl:
      threshold: 150

    errorlint:
      asserts: true
      comparison: true

    misspell:
      locale: US

  exclusions:
    rules:
      # Test files - exclude noisy linters
      - path: '(.+)_test\.go'
        linters:
          - dupl
          - errcheck
          - gocritic
          - gosec
      # Generated files
      - path: zz_generated
        linters:
          - all

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/maruina/aws-auth-manager

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
