apiVersion: v1
kind: Service
metadata: 
  name: {{ include "aws-auth-manager.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: {{ include "aws-auth-manager.fullname" . }}-controller-manager
    {{- include "aws-auth-manager.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: {{ include "aws-auth-manager.fullname" . }}-controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-auth-manager.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: {{ include "aws-auth-manager.fullname" . }}-controller-manager
    {{- include "aws-auth-manager.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: {{ include "aws-auth-manager.fullname" . }}-controller-manager