{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-auth-manager.serviceAccountName" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-auth-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
