name: Test Docker Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-build:
    name: test-docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64,arm

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
              ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{raw}}
          flavor: |
            latest=false

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to GitHub Packages
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build a docker image
        uses: docker/build-push-action@v3.0.0
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: ${{ steps.meta.outputs.tags }}
          push: false
